double **make_matrix(int, int);
double **growMatrix(double **, int);
int writeMatrix(double **, int, char *);
int GaussSeid1D(double *, double *, int, double);
int SOR2D(double **, double **, int, double);
double RBSOR2D(double **, double **, int, double);
void displayMatrix(double **, int);
double dabs(double);
double ***make_tensor(int, int, int);
double ***growTensor(double ***, int);
int RBSOR3D(double ***, double ***, int, double ***, int);
int testgrid3D(double ***, double ***, int, double ***, int);
double timer(int);
double amax(double *, int);
int argamax(double *, int);
int interpPsi2D(double **, double **, int);
double amax2D(double**, int);
double *argamax2D(double**, int, double *);
int RBSOR1D(double*, double*, int, double*, int);
int writeArray(double*, int, char*);
double amax3D(double ***, int);
double *argamax3D(double ***, int, double *);
int interpPsi3D(double ***, double ***, int);
