all:
	gcc main.c minmax.c lin_root.c quad_roots.c rcubic_roots.c rquartic_roots.c -o ex1c -lm
	gcc main.c minmax.c o_lin_root.c o_quad_roots.c o_rcubic_roots.c o_rquartic_roots.c -o o_ex1c -lm
	gcc mainQ3.c minmax.c lin_root.c quad_roots.c rcubic_roots.c rquartic_roots.c -o ex1cQ3 -lm
	gcc mainQ4.c minmax.c lin_root.c quad_roots.c rcubic_roots.c rquartic_roots.c -o ex1cQ4 -lm
	gcc mainMQ.c minmax.c lin_root.c quad_roots.c rcubic_roots.c rquartic_roots.c -o ex1cMQ -lm
